databases:
  - name: pomo-sync-sounds-db
    databaseName: pomo_sync_sounds_production
    user: pomo-sync-sounds-api
    region: singapore

services:
  - type: web
    name: pomo-sync-sounds-api
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pomo-sync-sounds-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
